apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-db-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        #key: prod/fastapi-app/db
        key: arn:aws:secretsmanager:us-east-1:854912240456:secret:rds!db-810c6db5-2f4e-40d3-b438-5300a1f373a1-mKr6PE
        property: DB_PASSWORD
